apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "tweet-cd.serviceLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{ if eq .Values.service.type "NodePort" }}nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "tweet-cd.selectorLabels" . | nindent 4 }}
